/** The exported Figma assets, in assets/context. Two photos are shared with the O demo's chefs. */
export const A = {
  avatar: require('../../assets/context/avatar.png'),
  cake: require('../../assets/context/cake.png'),
  caret16: require('../../assets/context/caret-16.svg'),
  caret18: require('../../assets/context/caret-18.svg'),
  caretLeft: require('../../assets/context/caret-left.svg'),
  caret: require('../../assets/context/caret.svg'),
  collage1: require('../../assets/context/collage-1.png'),
  collage2: require('../../assets/context/collage-2.png'),
  collage3: require('../../assets/context/collage-3.png'),
  collage4: require('../../assets/context/collage-4.png'),
  grapefruit: require('../../assets/context/grapefruit.png'),
  hero: require('../../assets/context/hero.png'),
  hero2: require('../../assets/context/hero2.png'),
  jacob: require('../../assets/context/jacob.png'),
  magnifier: require('../../assets/context/magnifier.svg'),
  play: require('../../assets/context/play.svg'),
  salad: require('../../assets/context/salad.png'),
  speaker: require('../../assets/context/speaker.svg'),
  wordmark: require('../../assets/context/toyon-wordmark.svg'),
  wagyu: require('../../assets/context/wagyu.png'),
  x: require('../../assets/context/x.svg'),
}
